# Generated by Django 5.1.2 on 2024-10-15 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_rename_desc_comment_content'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='desc',
            new_name='description',
        ),
    ]
