# Generated by Django 5.1.2 on 2024-10-18 11:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savatcha', '0002_remove_savat_descr_remove_savat_soni_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savat',
            name='mahsulot',
            field=models.ForeignKey(db_column='mahsulot_id', on_delete=django.db.models.deletion.CASCADE, to='savatcha.mahsulot'),
        ),
        migrations.RenameField(
            model_name='savat',
            old_name='mahsulot',
            new_name='mahsulot_id',
        ),
        migrations.AlterField(
            model_name='mahsulot',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
